---
- include_tasks: "{{ansible_os_family}}.yml"

- name: Copy agent properties file
  copy:
    src: autoregister.properties
    dest: /var/lib/go-agent/config

- name: Copy agent config file
  template:
    src: go-agent
    dest: /etc/default
    owner: root
    group: go
    mode: 0640
  notify: Start go-agent