---
- include_tasks: "{{ansible_os_family}}.yml"

- name: Copy agent properties file
  template:
    src: autoregister.properties
    dest: /var/lib/go-agent/config
    owner: root
    group: go
    mode: 0640

- name: Copy agent config file
  template:
    src: go-agent
    dest: /etc/default
    owner: root
    group: go
    mode: 0640
  notify: Start go-agent